### ISSUE TITLE
Implement checkLogin API to verify the user credentials and it will be part of login functionality.

### ISSUE THREAD

**Issue by TaniyaBhadauria** [GLEIF-IT/reg-pilot-webapp#100]

**Comment by aydarng** [comment]
When we send login request the response message will contain one of the following messages:
   1.  "Credential {said} presented for {aid} is cryptographically valid.". In this case we can proceed with the /checklogin requests flow.
   2.  "credential {said} from body of request did not cryptographically verify"`. In this case we can say that credential is not                                                        cryptographically valid and we can't proceed. But this case is impossible when we request a credential from browser extension.

After that we need to send /checklogin requests until we get one of the following messages in the response:
1. "unknown AID: {aid}". It means that we send the /checklogin request using unknown AID(the one which hasn't been used to login)
2. "AID {aid} w/ lei {acct.lei} presented valid credential". It means that we have been successfully logged in and can proceed with uploading reports.
3. "identifier {aid} presented credentials {state.said}, w/ status "Credential authorization expired", msg: {state.msg}".  It means that the auth session time has expired and you need to login again.
4.  "identifier {aid} has no access and no authorization being processed". In general it will mean that the auth session time has expired and you need to login again.
5.  "identifier {aid} presented credentials {state.said}, w/ status "Credential unauthorized", msg: {state.msg}".  It means that the authorization failed. The reason of failure you can get from `msg`. Possible `msg` values:
         - "Can't authorize cred with {Schema.schema_names[creder.schema]} schema". It means that credential is not an ECR credential. 
         - "Can't authorize cred with unknown schema {creder.schema}". It means that credential is not an ECR credential and the credential schema is unknown.
         - "unknown issuer {creder.issuer}". It means that the issuer of the credential has unknown AID.
         - "unknown issuee {creder.attrib["i"]}". It means that the credential issuee has unknown AID.
         - "LEI: {creder.attrib["LEI"]} not allowed". It means that the credential LEI is not presented in the list of allowed LEI's
         - "{creder.attrib["engagementContextRole"]} is not a valid submitter role". It means that the Engagement Context Role is not valid.
In case if you get "identifier {aid} presented credentials {state.said}, w/ status "Credential pending authorization", msg: {state.msg}" from the `/checklogin` response you'll need to keep sending `/checklogin` requests while you're getting this message("identifier {aid} presented credentials {state.said}, w/ status "Credential pending authorization"). It means that the authorization is pending.

**Comment by HunnySajid** [comment]
checklogin api integrated and merged
