### ISSUE TITLE
npm install Failing due to typeScript version conflict

### ISSUE THREAD

**Issue by ronakseth96** [GLEIF-IT/reg-pilot-webapp#46]
During the npm install process in the reg-pilot-web app project, we see an error due to a TypeScript version conflict. The error log indicates that the current TypeScript version specified in the devDependencies is incompatible with the version expected by react-scripts. We have the typescript version 5.4.5 specified in devDependencies, which may conflict with the version required by react-scripts@5.0.1.

**Error log:**
my-app % npm install
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: react-scripts@5.0.1
npm error Found: typescript@5.4.5
npm error node_modules/typescript
npm error   dev typescript@"^5.4.5" from the root project
npm error   peer typescript@">= 2.7" from fork-ts-checker-webpack-plugin@6.5.3
npm error   node_modules/fork-ts-checker-webpack-plugin
npm error     fork-ts-checker-webpack-plugin@"^6.5.0" from react-dev-utils@12.0.1
npm error     node_modules/react-dev-utils
npm error       react-dev-utils@"^12.0.1" from react-scripts@5.0.1
npm error       node_modules/react-scripts
npm error         react-scripts@"^5.0.1" from the root project
npm error   1 more (tsutils)
npm error
npm error Could not resolve dependency:
npm error peerOptional typescript@"^3.2.1 || ^4" from react-scripts@5.0.1
npm error node_modules/react-scripts
npm error   react-scripts@"^5.0.1" from the root project
npm error
npm error Conflicting peer dependency: typescript@4.9.5
npm error node_modules/typescript
npm error   peerOptional typescript@"^3.2.1 || ^4" from react-scripts@5.0.1
npm error   node_modules/react-scripts
npm error     react-scripts@"^5.0.1" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.

Could you please take a look at this?

**Comment by legend80s** [comment]
Add `overrides` if npm used as a workaround for this problem:

```json
// package.json
  "dependencies": {
    "typescript": "^5.8.3",
  },
  "// the upgrade of TypeScript to v5 (driven by ts-pattern) resulted the following error, because react-scripts pins it to v4, ": "",
  "// Could not resolve dependency: npm error peerOptional typescript@\"^3.2.1 || ^4\" from react-scripts@5.0.1": "",
  "// `overrides` are safer than `--force` or `--legacy-peer-deps` because they let you pin a specific dependency.": "",
  "overrides": {
    "typescript": "$typescript"
  },
```
