### ISSUE TITLE
User comes that does not have a valid wallet url/secret combination

### ISSUE THREAD

**Issue by 2byrds** [GLEIF-IT/reg-pilot-webapp#70]
User comes that does not have a valid wallet url/secret combination. Result: user should not be able to authenticate to the wallet. This is a wallet test really at the level of penetration test for wallets

**Comment by 2byrds** [comment]
@TaniyaBhadauria @HunnySajid  have we completed a test for this?

**Comment by HunnySajid** [comment]
Our e2e test suite covers this invalid wallet secret case.
