### ISSUE TITLE
OOR authentication after ECR authentication

### ISSUE THREAD

**Issue by 2byrds** [GLEIF-IT/reg-pilot-webapp#82]
Thank you to @HunnySajid for bringing this up. Should all logins replace previous logins? Perhaps we should have a test case where the user presents a valid ECR credential. But then later completes a login with an OOR credential. In that case the identifier is the same for both and right now the verification service will retain the valid ECR login and the user will be allowed to proceed through the UI flow (status/report-upload). But instead the API/verification service should probably reset the user authorization and then deny the status/report access.

**Comment by HunnySajid** [comment]
This is a demo video:
1- ECR credential is selected
2- Status Pages visit is allowed
3- Clear Credential
4- Select OOR credential
5- Can not access status page

https://www.loom.com/share/f0cae83bb4d4418e9da16a75112f1aab?sid=3ebd7085-0ecb-4799-8eae-87ec0463c87b
