### ISSUE TITLE
The UI/devops team will run through local setup of reg-pilot test scenarios to be used for webapp/deployment testing

### ISSUE THREAD

**Issue by 2byrds** [GLEIF-IT/reg-pilot-webapp#96]
If you are using the latest reg-pilot, from the signify-ts-test dir, you should be able to run 
```./test.sh --all```

- [x] This will start all the local docker services 
![image](https://github.com/user-attachments/assets/a5247e11-63e9-4009-a803-1544ccfbbea0)

- [x] It issues the credentials necessary. And you can see the passcode in the logs and configuration file that you can use to connect to your local keria instance 

![image](https://github.com/user-attachments/assets/48fdebb1-9da2-46f1-93ac-12393a352c89)
![image](https://github.com/user-attachments/assets/a308032f-74b7-46ba-9249-4dd9acef518a)
![image](https://github.com/user-attachments/assets/69a42112-c711-4e21-8012-2d72b56922d3)

- [ ] It then runs the signed report (and failure report) generation 
![image](https://github.com/user-attachments/assets/68793055-a7c5-4e63-b940-be697150796a)

- [ ] Once report generation is complete you will have a directory under test/data that has the AID of ecr1, which contains the signed reports. One of them will be called orig_bundle_somedate_somenumbers.zip which you could use 
![image](https://github.com/user-attachments/assets/f3b78ce1-706c-4d2c-b1ae-00f6c8f175ac)
![image](https://github.com/user-attachments/assets/a51aea4b-35d2-42bf-b377-75f41a2c3862)

- [ ] Finally it will run the signed and failure files through the reg-pilot-api.test.ts, similarly to how the UI would upload and get the status
![image](https://github.com/user-attachments/assets/cc11cefc-1573-456b-9d56-5656cbf3cdba)

Let @2byrds know when you have been able to run through this. You can then manually try uploads of signed reports from the UI as well, as long as you use the credential that the issuance produced in your local KERIA agent.

**Comment by HunnySajid** [comment]
@2byrds We have successfully executed the workflow to upload signed/failure files through the web app using agent created by running services locally. @ronakseth96 & I also demoed it on dev.
