### ISSUE TITLE
Could not find 'orig_bundle_20240827_13125_signed.zip' file

### ISSUE THREAD

**Issue by Jayharwani** [GLEIF-IT/reg-pilot-webapp#99]
I couldn't find the 'orig_bundle_20240827_13125_signed.zip' attached to the walkthrough/demo, I am going through the extension user flow to understand it and observe UX changes.

![{078E1065-B0FB-4C11-AA40-74723C88700D} 1](https://github.com/user-attachments/assets/8a989af0-a5a0-4c1e-a795-d67f99a6118c)

**Comment by 2byrds** [comment]
Thank you for reporting this @Jayharwani . I almost added the demo as a PR but decided against it as it will fall out of date quickly. But I have updated my branch with the file, for you. And I will link to the demo branch from the main repo in reg-pilot (not here in reg-pilot-webapp. see the update https://github.com/2byrds/reg-pilot/tree/demo_oct_2024/demo
